### ISSUE TITLE
Issue in latest release with package.json

### ISSUE THREAD

**Issue by dev-tim** [pyrsmk/qwest#42] opened 2015-03-11 15:06 UTC
There is misconfigured package.json which points to ```"main": "src/qwest.js",```
However in .npmignore there is excluded src folder:

```
.git/
.gitignore
nodes_modules/
src/
tests/
Gruntfile.js
package.json
```

**Comment by pyrsmk** [comment] 2015-03-11 15:36
Duplicate of #41

**Comment by pyrsmk** [comment] 2015-03-11 15:39
Sort of :p

**Comment by pyrsmk** [comment] 2015-03-11 15:46
Please update and tell me if it's working again

**Closed** 2015-03-11 16:16 UTC

**Comment by dev-tim** [comment] 2015-03-12 13:07
Thanks ;)

**Comment by pyrsmk** [comment] 2015-03-12 13:13
Np ;) Thanks for posting the issue.
